const localeKey = 'windline.locale';
const themeKey = 'windline.theme';

const ru = {
  appTitle: 'Windline · Рабочее место прогнозирования',
  appDescription: 'Почасовой прогноз для двух турбин, оценка качества и происхождение данных.',
  skipContent: 'Перейти к содержимому',
  workspaceNavigation: 'Навигация рабочего пространства',
  workspaceBrand: 'Рабочее место прогнозирования Windline',
  brandSubtitle: 'РАБОЧЕЕ МЕСТО ПРОГНОЗИРОВАНИЯ',
  monitor: 'НАБЛЮДЕНИЕ',
  navOverview: 'Обзор',
  navForecast: 'Прогноз',
  navBacktest: 'Историческая оценка',
  navTrace: 'Журнал агента',
  navQuality: 'Качество данных',
  localApi: 'Локальный API',
  connecting: 'Подключение',
  connected: 'Подключено',
  apiUnavailable: 'Недоступен',
  apiInterrupted: 'Связь прервана',
  apiRequestFailed: 'Ошибка запроса',
  powerOperations: 'ВЕТРОЭНЕРГЕТИКА / ОПЕРАЦИИ',
  selectedRun: 'Выбранный запуск',
  checkingMode: 'Проверка режима',
  demoMode: 'Демонстрационный режим',
  competitionMode: 'Соревновательный режим',
  offlineMode: 'БЕЗ СЕТИ',
  runSuccess: 'УСПЕШНО',
  runDegraded: 'С ОГРАНИЧЕНИЯМИ',
  runFailed: 'ОШИБКА',
  runUnknown: 'СТАТУС НЕИЗВЕСТЕН',
  apiFailed: 'API НЕДОСТУПЕН',
  noSavedRun: 'НЕТ СОХРАНЁННОГО ЗАПУСКА',
  noRun: 'НЕТ ЗАПУСКА',
  overviewKicker: 'ВЕТРОЭНЕРГЕТИКА / ПОЧАСОВЫЕ ОПЕРАЦИИ',
  overviewTitle: 'Рабочее место прогноза',
  overviewDescription: 'Почасовой прогноз двух турбин, диапазон неопределённости и подтверждающие данные.',
  currentRun: 'ТЕКУЩИЙ ЗАПУСК',
  loadingLatest: 'Загрузка последнего запуска',
  loadingLatestMessage: 'Загружаем последний сохранённый прогноз.',
  retryLatest: 'Повторить загрузку',
  selectedForecastFacts: 'Параметры выбранного прогноза',
  forecastHorizon: 'Горизонт прогноза',
  weatherSource: 'Источник погоды',
  evaluation: 'Оценка',
  unavailable: 'Недоступно',
  chartKicker: 'ПРОГНОЗ МОЩНОСТИ',
  chartTitle: 'Почасовой диапазон выработки',
  chartDescription: 'Нормированная выработка турбин: линия показывает p50, область — диапазон p10–p90.',
  awaitingRun: 'Ожидание запуска',
  noRunChart: 'НЕТ ЗАПУСКА',
  hoursUtc05: '{hours} ч · UTC+05',
  chartAria: 'Почасовой прогноз турбин',
  loadingChart: 'Загрузка графика прогноза',
  quantileRange: 'Диапазон p10–p90',
  medianLine: 'Медиана p50',
  bothTurbines: 'Обе серии построены по строкам прогноза, полученным от API.',
  chartEmpty: 'Для выбранного запуска нет данных прогноза.',
  chartSvgLabel: 'Почасовой прогноз по турбинам с диапазонами p10–p90',
  chartSvgTitle: 'Прогноз выработки и диапазон неопределённости',
  chartSvgDescription: 'Заштрихованная область показывает значения p10–p90 из ответа API; сплошная линия показывает p50. По горизонтали — часы от начала прогноза.',
  normalizedOutput: 'Нормированная выработка (%)',
  leadHours: '+{hours} ч',
  turbineOne: 'Турбина 01',
  turbineTwo: 'Турбина 02',
  chooseForecast: 'НОВЫЙ ПРОГНОЗ',
  chooseWindow: 'Выберите период',
  originLocalHelp: 'Начало прогноза укажите по местному времени. API получит соответствующее время UTC.',
  forecastOrigin: 'Начало прогноза',
  hourlyBoundary: 'Граница часа · {timezone}',
  localTimezone: 'местный часовой пояс',
  horizonLabel: 'Горизонт прогноза',
  hours24: '24 часа',
  hours48: '48 часов',
  generateForecast: 'Построить прогноз',
  freshForecast: 'Запустить новый прогноз',
  checkStatus: 'Проверить статус',
  requestPreparing: 'Подготовка запроса прогноза…',
  requestSubmitting: 'Отправка запроса прогноза…',
  jobQueued: 'Прогноз в очереди. Ожидаем локальный процесс.',
  jobRunning: 'Прогноз рассчитывается. Страница обновится после завершения.',
  jobFailed: 'Не удалось выполнить задачу прогноза.',
  failedRunSelected: 'Расчёт завершился ошибкой. Его запуск остаётся выбранным для просмотра.',
  reusedRun: 'Прогноз не изменился: API использовал сохранённый запуск.',
  forecastFinished: 'Прогноз готов. Показан запуск из ответа API.',
  connectionInterrupted: 'Связь прервана. Проверьте состояние задачи.',
  invalidOrigin: 'Укажите корректное начало прогноза на границе часа.',
  requestTimeout: 'Локальный API не ответил вовремя. Повторите запрос.',
  connectionError: 'Не удалось связаться с локальным API. Проверьте сервер и повторите запрос.',
  invalidApiResponse: 'API вернул ответ в неожиданном формате.',
  genericApiError: 'Не удалось выполнить запрос. Попробуйте ещё раз.',
  selectedRunHeading: 'ВЫБРАННЫЙ ЗАПУСК',
  waitingForApi: 'Ожидание ответа API',
  origin: 'Начало',
  reuse: 'Повторное использование',
  reusedUnchanged: 'Использован повторно · погода не изменилась',
  newForecastRun: 'Новый запуск прогноза',
  downloadSelectedCsv: 'Скачать CSV выбранного прогноза',
  forecastData: 'ДАННЫЕ ПРОГНОЗА',
  forecastRowsTitle: 'Почасовые строки прогноза',
  forecastRowsDescription: 'Точные значения p10, p50 и p90 из выбранного запуска. Значения показаны как доля нормированной выработки в процентах.',
  records: 'ЗАПИСИ',
  loadingRows: 'Загрузка строк',
  rowCount: '{count} строк прогноза',
  recordsUnavailable: 'Записи недоступны',
  downloadCsv: 'Скачать CSV',
  forecastRecordsAria: 'Таблица записей прогноза',
  scrollForecastTable: 'Прокручиваемая таблица прогноза',
  forecastTableCaption: 'Записи прогноза выбранного запуска. Квантили выработки нормированы и не указаны в мегаваттах.',
  validTime: 'Время прогноза (UTC+05)',
  turbine: 'Турбина',
  lead: 'Шаг',
  loadingForecastRows: 'Загрузка записей прогноза…',
  noForecastRows: 'Для этого запуска нет строк прогноза.',
  historicalEvidence: 'ИСТОРИЧЕСКИЕ ДАННЫЕ',
  backtestTitle: 'Историческая оценка',
  backtestDescription: 'Метрики загружаются из выбранного запуска. Точность показывается только при наличии сопоставленных наблюдений турбин.',
  evaluationStatus: 'СТАТУС ОЦЕНКИ',
  checkingEvaluation: 'Проверка периода оценки',
  awaitingEvaluation: 'Ожидание запуска',
  evaluationNotLoaded: 'Оценка ещё не загружена',
  historicalMetricsAppear: 'Исторические метрики появятся, если выбранный запуск содержит размеченные наблюдения.',
  historicalEvaluationCaption: 'Метрики исторической оценки прогноза в нормированных единицах выработки.',
  model: 'Модель',
  scope: 'Объём данных',
  mae: 'MAE',
  rmse: 'RMSE',
  intervalCoverage: 'Покрытие интервала',
  rows: 'Строки',
  noFebruaryTruth: 'Фактические данные турбин за февраль недоступны; точность за февраль не рассчитывается.',
  metricsAvailable: 'Метрики доступны',
  noMatchingLabels: 'Нет сопоставленных наблюдений турбин',
  noMatchingLabelsDescription: 'Метрики недоступны: в выбранном запуске нет совпадающих наблюдений выработки турбин.',
  provenanceWithheld: 'Оценка скрыта из-за происхождения данных',
  provenanceWithheldDescription: 'Доступность погодного архива до начала каждого прогноза не подтверждена.',
  historicalUnavailable: 'Исторические метрики недоступны',
  historicalUnavailableDescription: 'В этом запуске нет пригодных записей исторической оценки.',
  noRunSelected: 'Запуск не выбран',
  loadRunForEvaluation: 'Загрузите сохранённый прогноз или создайте запуск, чтобы проверить историческую оценку.',
  allTurbines: 'Все турбины',
  allLeads: 'Все шаги',
  runDecisions: 'РЕШЕНИЯ ЗАПУСКА',
  agentTraceTitle: 'Журнал агента',
  agentTraceDescription: 'Порядок действий и результаты выбранного запуска. Объяснения сформированы по структурированным данным.',
  selectedRunTrace: 'Журнал событий выбранного запуска',
  loadingEventTrace: 'Загрузка журнала событий…',
  agentEvents: 'События запуска агента',
  loadingAgentEvents: 'Загрузка событий агента',
  noEventTrace: 'Нет журнала событий',
  noEventTraceDescription: 'Выбранный запуск не содержит событий агента.',
  eventCount: '{count} событий · {runId}',
  recordedEvents: '{count} событий записано',
  eventSummary: 'Шаг {number}: {action} · {outcome}',
  agentRecorded: 'Записанное действие',
  step: 'Шаг',
  eventSucceeded: 'выполнено',
  eventFailed: 'не выполнено',
  eventSkipped: 'пропущено',
  eventStarted: 'начато',
  eventUnknown: 'записано',
  technicalDetails: 'Технические детали',
  rawReason: 'Исходная запись',
  action: 'Действие',
  duration: 'Длительность',
  durationUnavailable: 'Длительность недоступна',
  noRunForTrace: 'Загрузите сохранённый прогноз или создайте запуск, чтобы просмотреть решения.',
  provenanceInputs: 'ПРОИСХОЖДЕНИЕ ДАННЫХ И ИСТОЧНИКИ',
  qualityTitle: 'Качество данных',
  qualityDescription: 'Источник, давность наблюдений и проверка доступности до прогноза взяты из манифеста выбранного запуска.',
  pointInTimeCheck: 'ПРОВЕРКА ДО НАЧАЛА ПРОГНОЗА',
  loadingProvenance: 'Загрузка происхождения данных',
  qualityAria: 'Качество данных прогноза и происхождение погоды',
  qualityDetails: 'Сведения о качестве данных',
  loadingWeatherSource: 'Загрузка источника погоды',
  competitionGateNote: 'Допуск к соревнованию определяет проверка происхождения данных на стороне сервера.',
  demoOnly: 'Только демонстрация',
  verified: 'Проверено',
  unverified: 'Не проверено',
  provenancePassed: 'Проверка происхождения данных для этого запуска пройдена.',
  provenanceUnverified: 'Доступность исходного выпуска погоды не подтверждена.',
  qualityNotSelected: 'Загрузка прогноза или создание запуска позволит проверить происхождение данных.',
  apiMode: 'Режим API',
  weatherProvider: 'Поставщик погоды',
  weatherModel: 'Модель погоды',
  archiveClassification: 'Класс архива',
  weatherIssueTime: 'Время выпуска прогноза погоды',
  weatherAvailableAt: 'Время доступности погоды',
  retrievedAt: 'Время получения',
  latestObservation: 'Последнее наблюдение',
  observationAge: 'Давность наблюдений',
  staleObservations: 'Устаревшие наблюдения',
  historyRows: 'Строк истории',
  competitionEligibility: 'Допуск к соревнованию',
  yes: 'Да',
  no: 'Нет',
  hours: '{value} ч',
  evaluationUnavailable: 'Оценка недоступна',
  evaluationNoLabels: 'Нет наблюдений',
  metricStatusAvailable: 'Доступна',
  evaluationWindowUnavailable: 'Период оценки недоступен',
  dateRange: '{start} — {end}',
  unavailableNoLabels: 'нет_наблюдений',
  unavailableUnverifiedWeather: 'погода_не_проверена',
  successCode: 'успешно',
  degradedCode: 'с_ограничениями',
  failedCode: 'ошибка',
  emptyForecastFailure: 'Строки прогноза недоступны',
  emptyForecast: 'Здесь появятся данные, когда будет выбран запуск прогноза.',
  forecastFailedAlert: 'Расчёт прогноза завершился ошибкой. Запуск остаётся выбранным для просмотра.',
  forecastDegradedAlert: 'Прогноз ограничен. Перед использованием проверьте происхождение погодных данных и качество наблюдений.',
  demoAlert: 'API работает в демонстрационном режиме. Используйте прогноз только для демонстрации.',
  eligibilityAlert: 'Доступность погодных данных на момент выпуска не подтверждена.',
  noSavedRunAlert: 'Сохранённых прогнозов пока нет. Укажите начало на границе часа и постройте прогноз.',
  apiUnavailableAlert: 'Последний запуск недоступен. Проверьте локальный API и повторите запрос.',
  localForecastDesk: 'ЛОКАЛЬНЫЙ ПРОГНОЗНЫЙ ПУЛЬТ',
  footerApiNote: 'Строки прогноза, оценка и происхождение данных поступают от локального API.',
  languageLabel: 'Язык интерфейса',
  themeLabel: 'Тема интерфейса',
  switchToDark: 'Включить тёмную тему',
  switchToLight: 'Включить светлую тему',
  sectionNavigation: 'Разделы панели',
  unitUnavailable: 'Недоступно',
  unitHours: 'ч',
  unitMilliseconds: 'мс',
  metricUnavailable: 'Нет данных',
  scopeAll: 'Все',
  statusNoLabels: 'нет наблюдений',
  statusUnverifiedWeather: 'погода не проверена',
  eventStart: 'Запуск',
  eventForecast: 'Расчёт прогноза',
  eventWeather: 'Получение погоды',
  eventValidate: 'Проверка данных',
  eventFeatures: 'Подготовка признаков',
  eventModel: 'Расчёт модели',
  eventBacktest: 'Историческая оценка',
  eventPersist: 'Сохранение результата',
  eventReuse: 'Повторное использование запуска',
  eventComplete: 'Завершение запуска',
  footerBrand: 'WINDLINE',
  railTagline: 'Энергия ветра — ясность в каждом прогнозе.',
  heroCapabilities: 'Возможности прогноза',
  heroTwoTurbines: 'Две турбины',
  hero24And48: 'Горизонт 24 / 48 ч',
  heroQuantiles: 'Диапазон p10–p90',
  heroImageCaption: 'Энергия ветра для чистого завтра',
  turbineCount: 'Турбины',
  viewForecastRows: 'Все строки',
  forecastSummary: 'Сводка выбранного прогноза',
  latestMedian: 'Последнее значение p50',
  forecastRows: 'Строки прогноза',
  returnedByApi: 'Получено от API',
  predictionInterval: 'Интервал прогноза',
  returnedQuantiles: 'Квантили из API',
};

const kk = {
  appTitle: 'Windline · Болжам жұмыс кеңістігі',
  appDescription: 'Екі турбинаға арналған сағаттық болжам, бағалау және деректердің шығу тегі.',
  skipContent: 'Негізгі мазмұнға өту',
  workspaceNavigation: 'Жұмыс кеңістігінің навигациясы',
  workspaceBrand: 'Windline болжам жұмыс кеңістігі',
  brandSubtitle: 'БОЛЖАМ ЖҰМЫС КЕҢІСТІГІ',
  monitor: 'БАҚЫЛАУ',
  navOverview: 'Шолу',
  navForecast: 'Болжам',
  navBacktest: 'Тарихи бағалау',
  navTrace: 'Агент журналы',
  navQuality: 'Деректер сапасы',
  localApi: 'Жергілікті API',
  connecting: 'Қосылуда',
  connected: 'Қосылды',
  apiUnavailable: 'Қолжетімсіз',
  apiInterrupted: 'Байланыс үзілді',
  apiRequestFailed: 'Сұрау қатесі',
  powerOperations: 'ЖЕЛ ЭНЕРГИЯСЫ / ОПЕРАЦИЯЛАР',
  selectedRun: 'Таңдалған іске қосу',
  checkingMode: 'Режим тексерілуде',
  demoMode: 'Көрсету режимі',
  competitionMode: 'Жарыс режимі',
  offlineMode: 'ЖЕЛІСІЗ',
  runSuccess: 'СӘТТІ',
  runDegraded: 'ШЕКТЕУЛІ',
  runFailed: 'ҚАТЕ',
  runUnknown: 'КҮЙІ БЕЛГІСІЗ',
  apiFailed: 'API ҚОЛЖЕТІМСІЗ',
  noSavedRun: 'САҚТАЛҒАН ІСКЕ ҚОСУ ЖОҚ',
  noRun: 'ІСКЕ ҚОСУ ЖОҚ',
  overviewKicker: 'ЖЕЛ ЭНЕРГИЯСЫ / САҒАТТЫҚ ОПЕРАЦИЯЛАР',
  overviewTitle: 'Болжам жұмыс кеңістігі',
  overviewDescription: 'Екі турбинаның сағаттық болжамы, белгісіздік ауқымы және оны растайтын деректер.',
  currentRun: 'АҒЫМДАҒЫ ІСКЕ ҚОСУ',
  loadingLatest: 'Соңғы іске қосу жүктелуде',
  loadingLatestMessage: 'Соңғы сақталған болжам оқылуда.',
  retryLatest: 'Қайта жүктеу',
  selectedForecastFacts: 'Таңдалған болжам параметрлері',
  forecastHorizon: 'Болжам көкжиегі',
  weatherSource: 'Ауа райы көзі',
  evaluation: 'Бағалау',
  unavailable: 'Қолжетімсіз',
  chartKicker: 'ҚУАТ БОЛЖАМЫ',
  chartTitle: 'Сағаттық өндіріс ауқымы',
  chartDescription: 'Турбинаның нормаланған өндірісі: сызық p50 мәнін, боялған аймақ p10–p90 ауқымын көрсетеді.',
  awaitingRun: 'Іске қосу күтілуде',
  noRunChart: 'ІСКЕ ҚОСУ ЖОҚ',
  hoursUtc05: '{hours} сағ · UTC+05',
  chartAria: 'Турбиналардың сағаттық болжамы',
  loadingChart: 'Болжам диаграммасы жүктелуде',
  quantileRange: 'p10–p90 ауқымы',
  medianLine: 'p50 медианасы',
  bothTurbines: 'Екі қатар да API қайтарған болжам жолдарынан салынған.',
  chartEmpty: 'Таңдалған іске қосуда болжам деректері жоқ.',
  chartSvgLabel: 'p10–p90 белгісіздік ауқымдары бар турбиналардың сағаттық болжамы',
  chartSvgTitle: 'Өндіріс болжамы және белгісіздік ауқымы',
  chartSvgDescription: 'Боялған аймақ API жауабындағы p10–p90 мәндерін, тұтас сызық p50 мәнін көрсетеді. Көлденең осьте болжам басталғаннан бергі сағаттар берілген.',
  normalizedOutput: 'Нормаланған өндіріс (%)',
  leadHours: '+{hours} сағ',
  turbineOne: 'Турбина 01',
  turbineTwo: 'Турбина 02',
  chooseForecast: 'ЖАҢА БОЛЖАМ',
  chooseWindow: 'Кезеңді таңдаңыз',
  originLocalHelp: 'Болжамның басталу уақытын жергілікті уақытпен енгізіңіз. API балама UTC уақытын алады.',
  forecastOrigin: 'Болжамның басталуы',
  hourlyBoundary: 'Сағат шегі · {timezone}',
  localTimezone: 'жергілікті уақыт белдеуі',
  horizonLabel: 'Болжам көкжиегі',
  hours24: '24 сағат',
  hours48: '48 сағат',
  generateForecast: 'Болжам құру',
  freshForecast: 'Жаңа болжамды іске қосу',
  checkStatus: 'Күйін тексеру',
  requestPreparing: 'Болжам сұрауы дайындалуда…',
  requestSubmitting: 'Болжам сұрауы жіберілуде…',
  jobQueued: 'Болжам кезекте. Жергілікті процесс күтілуде.',
  jobRunning: 'Болжам есептелуде. Аяқталған соң бет жаңартылады.',
  jobFailed: 'Болжам тапсырмасы орындалмады.',
  failedRunSelected: 'Есептеу қатемен аяқталды. Тексеру үшін осы іске қосу таңдалған күйде қалады.',
  reusedRun: 'Болжам өзгермеді: API сақталған іске қосуды пайдаланды.',
  forecastFinished: 'Болжам дайын. API жауабындағы іске қосу таңдалды.',
  connectionInterrupted: 'Байланыс үзілді. Тапсырма күйін тексеріңіз.',
  invalidOrigin: 'Болжамның басталу уақытын сағат шегіне дәл енгізіңіз.',
  requestTimeout: 'Жергілікті API уақытында жауап бермеді. Сұрауды қайталаңыз.',
  connectionError: 'Жергілікті API-ге қосылмады. Серверді тексеріп, қайталап көріңіз.',
  invalidApiResponse: 'API күтпеген пішімде жауап қайтарды.',
  genericApiError: 'Сұрауды орындау мүмкін болмады. Қайталап көріңіз.',
  selectedRunHeading: 'ТАҢДАЛҒАН ІСКЕ ҚОСУ',
  waitingForApi: 'API жауабы күтілуде',
  origin: 'Басталуы',
  reuse: 'Қайта пайдалану',
  reusedUnchanged: 'Қайта пайдаланылды · ауа райы өзгермеген',
  newForecastRun: 'Жаңа болжам іске қосуы',
  downloadSelectedCsv: 'Таңдалған болжамның CSV файлын жүктеу',
  forecastData: 'БОЛЖАМ ДЕРЕКТЕРІ',
  forecastRowsTitle: 'Болжамның сағаттық жолдары',
  forecastRowsDescription: 'Таңдалған іске қосудан алынған p10, p50 және p90 мәндері. Нормаланған өндіріс үлестері пайызбен көрсетілген.',
  records: 'ЖАЗБАЛАР',
  loadingRows: 'Жолдар жүктелуде',
  rowCount: 'Болжам жолы: {count}',
  recordsUnavailable: 'Жазбалар қолжетімсіз',
  downloadCsv: 'CSV жүктеу',
  forecastRecordsAria: 'Болжам жазбаларының кестесі',
  scrollForecastTable: 'Жылжытылатын болжам кестесі',
  forecastTableCaption: 'Таңдалған іске қосудың болжам жазбалары. Өндіріс квантильдері нормаланған, мегаваттпен берілмеген.',
  validTime: 'Болжам уақыты (UTC+05)',
  turbine: 'Турбина',
  lead: 'Қадам',
  loadingForecastRows: 'Болжам жазбалары жүктелуде…',
  noForecastRows: 'Бұл іске қосуда болжам жолдары жоқ.',
  historicalEvidence: 'ТАРИХИ ДЕРЕКТЕР',
  backtestTitle: 'Тарихи бағалау',
  backtestDescription: 'Метрикалар таңдалған іске қосудан алынады. Дәлдік тек турбина бойынша сәйкес бақылаулар болғанда көрсетіледі.',
  evaluationStatus: 'БАҒАЛАУ КҮЙІ',
  checkingEvaluation: 'Бағалау кезеңі тексерілуде',
  awaitingEvaluation: 'Іске қосу күтілуде',
  evaluationNotLoaded: 'Бағалау әлі жүктелмеді',
  historicalMetricsAppear: 'Таңдалған іске қосуда белгіленген бақылаулар болса, тарихи метрикалар осында көрсетіледі.',
  historicalEvaluationCaption: 'Өндірістің нормаланған бірліктеріндегі тарихи болжам бағалау метрикалары.',
  model: 'Модель',
  scope: 'Деректер көлемі',
  mae: 'MAE',
  rmse: 'RMSE',
  intervalCoverage: 'Интервалды қамту',
  rows: 'Жолдар',
  noFebruaryTruth: 'Ақпан айындағы турбиналардың нақты деректері жоқ; ақпан дәлдігі есептелмейді.',
  metricsAvailable: 'Метрикалар қолжетімді',
  noMatchingLabels: 'Сәйкес турбина бақылаулары жоқ',
  noMatchingLabelsDescription: 'Метрикалар қолжетімсіз: таңдалған іске қосуда өндірістің сәйкес бақылаулары жоқ.',
  provenanceWithheld: 'Деректер шығу тегіне байланысты бағалау жасырылды',
  provenanceWithheldDescription: 'Әр болжам басталғанға дейін ауа райы архивінің қолжетімді болғаны расталмады.',
  historicalUnavailable: 'Тарихи метрикалар қолжетімсіз',
  historicalUnavailableDescription: 'Бұл іске қосуда жарамды тарихи бағалау жазбалары жоқ.',
  noRunSelected: 'Іске қосу таңдалмаған',
  loadRunForEvaluation: 'Тарихи бағалауды көру үшін сақталған болжамды жүктеңіз немесе жаңасын жасаңыз.',
  allTurbines: 'Барлық турбиналар',
  allLeads: 'Барлық қадамдар',
  runDecisions: 'ІСКЕ ҚОСУ ШЕШІМДЕРІ',
  agentTraceTitle: 'Агент журналы',
  agentTraceDescription: 'Таңдалған іске қосудың әрекеттер реті мен нәтижелері. Түсіндірмелер құрылымдық деректерден жасалады.',
  selectedRunTrace: 'Таңдалған іске қосу оқиғаларының журналы',
  loadingEventTrace: 'Оқиғалар журналы жүктелуде…',
  agentEvents: 'Агент іске қосу оқиғалары',
  loadingAgentEvents: 'Агент оқиғалары жүктелуде',
  noEventTrace: 'Оқиғалар журналы жоқ',
  noEventTraceDescription: 'Таңдалған іске қосуда агент оқиғалары жоқ.',
  eventCount: '{count} оқиға · {runId}',
  recordedEvents: '{count} оқиға жазылды',
  eventSummary: '{number}-қадам: {action} · {outcome}',
  agentRecorded: 'Тіркелген әрекет',
  step: 'Қадам',
  eventSucceeded: 'орындалды',
  eventFailed: 'орындалмады',
  eventSkipped: 'өткізілді',
  eventStarted: 'басталды',
  eventUnknown: 'тіркелді',
  technicalDetails: 'Техникалық деректер',
  rawReason: 'Бастапқы жазба',
  action: 'Әрекет',
  duration: 'Ұзақтығы',
  durationUnavailable: 'Ұзақтығы қолжетімсіз',
  noRunForTrace: 'Шешімдерді көру үшін сақталған болжамды жүктеңіз немесе жаңасын жасаңыз.',
  provenanceInputs: 'ДЕРЕКТЕР ШЫҒУ ТЕГІ ЖӘНЕ КІРІС ДЕРЕКТЕР',
  qualityTitle: 'Деректер сапасы',
  qualityDescription: 'Көз, бақылаулардың ескіруі және болжамға дейінгі қолжетімділік тексерісі таңдалған іске қосу манифестінен алынады.',
  pointInTimeCheck: 'БОЛЖАМҒА ДЕЙІНГІ ТЕКСЕРУ',
  loadingProvenance: 'Деректер шығу тегі жүктелуде',
  qualityAria: 'Болжам деректерінің сапасы және ауа райының шығу тегі',
  qualityDetails: 'Деректер сапасы туралы мәлімет',
  loadingWeatherSource: 'Ауа райы көзі жүктелуде',
  competitionGateNote: 'Жарысқа сәйкестікті сервердегі деректер шығу тегін тексеру анықтайды.',
  demoOnly: 'Тек көрсету үшін',
  verified: 'Тексерілді',
  unverified: 'Тексерілмеді',
  provenancePassed: 'Осы іске қосу үшін деректер шығу тегінің тексерісі өтті.',
  provenanceUnverified: 'Ауа райы болжамының бастапқы шығарылымы қолжетімді болғаны расталмады.',
  qualityNotSelected: 'Деректер шығу тегін көру үшін болжамды жүктеңіз немесе іске қосуды бастаңыз.',
  apiMode: 'API режимі',
  weatherProvider: 'Ауа райы жеткізушісі',
  weatherModel: 'Ауа райы моделі',
  archiveClassification: 'Архив санаты',
  weatherIssueTime: 'Ауа райы болжамының шыққан уақыты',
  weatherAvailableAt: 'Ауа райы қолжетімді болған уақыт',
  retrievedAt: 'Алынған уақыты',
  latestObservation: 'Соңғы бақылау',
  observationAge: 'Бақылаулардың ескіруі',
  staleObservations: 'Ескірген бақылаулар',
  historyRows: 'Тарих жолдары',
  competitionEligibility: 'Жарысқа сәйкестік',
  yes: 'Иә',
  no: 'Жоқ',
  hours: '{value} сағ',
  evaluationUnavailable: 'Бағалау қолжетімсіз',
  evaluationNoLabels: 'Бақылаулар жоқ',
  metricStatusAvailable: 'Қолжетімді',
  evaluationWindowUnavailable: 'Бағалау кезеңі қолжетімсіз',
  dateRange: '{start} — {end}',
  unavailableNoLabels: 'бақылаулар_жоқ',
  unavailableUnverifiedWeather: 'ауа_райы_тексерілмеген',
  successCode: 'сәтті',
  degradedCode: 'шектеулі',
  failedCode: 'қате',
  emptyForecastFailure: 'Болжам жолдары қолжетімсіз',
  emptyForecast: 'Болжамды іске қосу таңдалғанда деректер осында көрсетіледі.',
  forecastFailedAlert: 'Болжам есебі сәтсіз аяқталды. Тексеру үшін бұл іске қосу таңдалған күйде қалады.',
  forecastDegradedAlert: 'Болжам шектеулі. Қолданар алдында ауа райы деректерінің шығу тегін және бақылаулар сапасын тексеріңіз.',
  demoAlert: 'API көрсету режимінде жұмыс істеп тұр. Болжамды тек көрсету үшін пайдаланыңыз.',
  eligibilityAlert: 'Ауа райы деректерінің шығарылған сәтте қолжетімді болғаны расталмады.',
  noSavedRunAlert: 'Әзірше сақталған болжам жоқ. Сағат шегіндегі басталу уақытын көрсетіп, болжам құрыңыз.',
  apiUnavailableAlert: 'Соңғы іске қосу қолжетімсіз. Жергілікті API-ді тексеріп, сұрауды қайталаңыз.',
  localForecastDesk: 'ЖЕРГІЛІКТІ БОЛЖАМ БАСҚАРУ ОРТАЛЫҒЫ',
  footerApiNote: 'Болжам жолдары, бағалау және деректер шығу тегі жергілікті API-ден алынады.',
  languageLabel: 'Интерфейс тілі',
  themeLabel: 'Интерфейс тақырыбы',
  switchToDark: 'Қараңғы тақырыпты қосу',
  switchToLight: 'Ашық тақырыпты қосу',
  sectionNavigation: 'Панель бөлімдері',
  unitUnavailable: 'Қолжетімсіз',
  unitHours: 'сағ',
  unitMilliseconds: 'мс',
  metricUnavailable: 'Дерек жоқ',
  scopeAll: 'Барлығы',
  statusNoLabels: 'бақылаулар жоқ',
  statusUnverifiedWeather: 'ауа райы тексерілмеген',
  eventStart: 'Іске қосу',
  eventForecast: 'Болжам есептеу',
  eventWeather: 'Ауа райын алу',
  eventValidate: 'Деректерді тексеру',
  eventFeatures: 'Белгілерді дайындау',
  eventModel: 'Модель есебі',
  eventBacktest: 'Тарихи бағалау',
  eventPersist: 'Нәтижені сақтау',
  eventReuse: 'Іске қосуды қайта пайдалану',
  eventComplete: 'Іске қосуды аяқтау',
  footerBrand: 'WINDLINE',
  railTagline: 'Жел қуаты — әр болжамда айқындық.',
  heroCapabilities: 'Болжам мүмкіндіктері',
  heroTwoTurbines: 'Екі турбина',
  hero24And48: '24 / 48 сағат көкжиегі',
  heroQuantiles: 'p10–p90 ауқымы',
  heroImageCaption: 'Таза ертеңге арналған жел қуаты',
  turbineCount: 'Турбиналар',
  viewForecastRows: 'Барлық жолдар',
  forecastSummary: 'Таңдалған болжамның қысқаша мазмұны',
  latestMedian: 'Соңғы p50 мәні',
  forecastRows: 'Болжам жолдары',
  returnedByApi: 'API қайтарды',
  predictionInterval: 'Болжам аралығы',
  returnedQuantiles: 'API қайтарған квантильдер',
};

export const messages = { ru, kk };
export const defaultLocale = 'ru';

export function text(locale, key, values = {}) {
  const template = messages[locale]?.[key] ?? messages.ru[key] ?? key;
  return template.replace(/\{(\w+)\}/g, (_, name) => String(values[name] ?? ''));
}

export function readLocale(storage) {
  try {
    const value = storage?.getItem(localeKey);
    return value === 'kk' || value === 'ru' ? value : defaultLocale;
  } catch {
    return defaultLocale;
  }
}

export function saveLocale(locale, storage) {
  try {
    storage?.setItem(localeKey, locale === 'kk' ? 'kk' : 'ru');
  } catch {
    // Storage can be disabled in private browsing or embedded contexts.
  }
}

export function readTheme(storage) {
  try {
    const value = storage?.getItem(themeKey);
    return value === 'light' || value === 'dark' ? value : 'system';
  } catch {
    return 'system';
  }
}

export function resolveTheme(preference, prefersDark) {
  if (preference === 'dark' || preference === 'light') return preference;
  return prefersDark ? 'dark' : 'light';
}

export function saveTheme(theme, storage) {
  try {
    storage?.setItem(themeKey, theme === 'dark' ? 'dark' : 'light');
  } catch {
    // The active theme still changes for this page when storage is unavailable.
  }
}

export function toggleTheme(currentTheme, storage) {
  const next = currentTheme === 'dark' ? 'light' : 'dark';
  saveTheme(next, storage);
  return next;
}
