[theme]
base = "light"
primaryColor = "#13736D"
backgroundColor = "#F6F9FA"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#18343B"
font = "sans serif"

[server]
headless = true

[client]
toolbarMode = "minimal"
